theme: jekyll-theme-midnight
title: Dead Physicists Society
description: 

jayme3title: III Escola Jayme Tiomno de Física Teórica
jayme4title: IV Escola de Física Jayme Tiomno
jayme5title: V Escola de Física Jayme Tiomno
jayme6title: VI Escola de Física Jayme Tiomno

github:
  is_project_page: false

collections:
  workshops:
    output: true
    
defaults:
  - scope:
      path: ""
      type: "workshops"
    values:
      layout: "workshop3"
  - scope:
      path: "jayme"
      type: "pages"
    values:
      layout: "jayme6"      
  - scope:
      path: ""
    values:
      layout: "default"
